version: "3"

services:
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_ROOT_DATABASE: sheltr
      MONGO_INITDB_DATABASE: sheltr
    ports:
      - "27017:27017"
    # volumes:
    # - ./db/mongo-auth.js:/docker-entrypoint-initdb.d/mongo-auth.js:ro
    # - ./db/mongo-loaddata.sh:/docker-entrypoint-initdb.d/mongo-loaddata.sh:ro
    # - ./db/suburb.json:/docker-entrypoint-initdb.d/suburb.json:ro
    # - ./db/uni_for_mongo.txt:/docker-entrypoint-initdb.d/uni_for_mongo.txt:ro
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - db
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
