name: 3. Load Mongo data
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Mongo tools install
        run: |
          curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
          sudo apt update
          sudo apt install -y mongodb-org
      - name: Import universities
        run: |
          mongoimport --authenticationDatabase=admin --host pztest-db.chintogtokh.com:27017 --username $MONGO_DBUSER --password $MONGO_DBPASS --drop --legacy --db sheltr --collection admin --type json --file uni_for_mongo.txt
        env:
          MONGO_DBUSER: ${{ secrets.MONGO_DBUSER }}
          MONGO_DBPASS: ${{ secrets.MONGO_DBPASS }}
