name: 3. Load Mongo data
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Mongo tools install
        run: |
          curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
          sudo apt update
          sudo apt install -y mongodb-org
      - name: Download universities
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://www.chintogtokh.com/uni_for_mongo.txt
          destination: ./uni_for_mongo.txt
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
      - name: Import universities
        run: |
          mongoimport --authenticationDatabase=admin --host pztest-db.chintogtokh.com:27017 --username $MONGO_DBUSER --password $MONGO_DBPASS --drop --legacy --db admin --collection universities --type json --file uni_for_mongo.txt
        env:
          MONGO_DBUSER: ${{ secrets.MONGO_DBUSER }}
          MONGO_DBPASS: ${{ secrets.MONGO_DBPASS }}
      - name: Download suburbs
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://www.chintogtokh.com/suburb.json
          destination: ./suburb.json
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
      - name: Import suburbs
        run: |
          mongoimport --authenticationDatabase=admin --host pztest-db.chintogtokh.com:27017 --username $MONGO_DBUSER --password $MONGO_DBPASS --drop --legacy --db admin --collection suburbs --type json --file suburb.json
        env:
          MONGO_DBUSER: ${{ secrets.MONGO_DBUSER }}
          MONGO_DBPASS: ${{ secrets.MONGO_DBPASS }}
      - name: Download lang
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://www.chintogtokh.com/languages.json
          destination: ./languages.json
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
      - name: Import lang
        run: |
          mongoimport --authenticationDatabase=admin --host pztest-db.chintogtokh.com:27017 --username $MONGO_DBUSER --password $MONGO_DBPASS --drop --legacy --db admin --collection languages --type json --file languages.json
        env:
          MONGO_DBUSER: ${{ secrets.MONGO_DBUSER }}
          MONGO_DBPASS: ${{ secrets.MONGO_DBPASS }}
