name: 3. Load Mongo data
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Mongo tools install
        run: |
          sudo apt install -y mongodb-org
      - name: Import universities
        run: |
          mongoimport --host pztest-db.chintogtokh.com:27017 --username $MONGO_DBUSER --password $MONGO_DBPASS --drop --legacy --db sheltr --collection universities --type json --file uni_for_mongo.txt
        env:
          MONGO_DBUSER: ${{ secrets.MONGO_DBUSER }}
          MONGO_DBPASS: ${{ secrets.MONGO_DBPASS }}
